# Generated by Django 5.2.12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='replies',
                to='interactions.comment',
            ),
        ),
        migrations.AddField(
            model_name='articleshare',
            name='platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'parent'], name='comments_article_parent_idx'),
        ),
    ]
